// Auto-generated by typewriter from C# controller

import { ApiService } from "../ApiServices/ApiService";
import { ApiServiceCancelator } from "../ApiServices/ApiServiceCancelator";

export default class CoreApiService {
    public static index = (cancelator?: ApiServiceCancelator): Promise<any> => {
        return ApiService.request({
            url: `api/Core/`,
            method: "get",
            data: null
        }, cancelator);
    }

}