// Auto-generated by typewriter from C# controller

import { ApiService } from "../ApiServices/ApiService";
import { ApiServiceCancelator } from "../ApiServices/ApiServiceCancelator";

export default class EventApiService {
    public static getAll = (cancelator?: ApiServiceCancelator): Promise<any> => {
        return ApiService.request({
            url: `api/Event/`,
            method: "get",
            data: null
        }, cancelator);
    }

    public static post = (e: Event, cancelator?: ApiServiceCancelator): Promise<any> => {
        return ApiService.request({
            url: `api/Event/`,
            method: "post",
            data: e
        }, cancelator);
    }

}